#!/bin/bash

export LC_CTYPE=en_US.UTF-8
export JAVA_HOME=/data/jdk8

_repo=$1
_rev=$2

_pwd=`dirname $0`
_author=`svnlook author $_repo`
_comment=`svnlook log $_repo`
_date=`svnlook date $_repo`
_email=$_author@wcce.cn
_findbugs=/data/findbugs-3.0.1/bin/findbugs
_ant=/data/apache-ant-1.9.4/bin/ant
_sendmail=$_pwd/mail.pl
_getname=$_pwd/get_name.pl
_getclass=$_pwd/get_class.pl

_pro_name=`svnlook changed $_repo |$_getname`
test -n "$_pro_name" || exit 1
echo -e "project name: $_pro_name\n"

_class_str=`svnlook changed $_repo |$_getclass`
test -n "$_class_str" || exit 2
echo -e "classes: $_class_str\n"

test -d $_pwd/$_pro_name || exit 3
cd $_pwd/$_pro_name && svn up --username deploy --password 123456 --no-auth-cache && _bug=`$_ant` && _bug=`$_findbugs -textui -project *.fbp -onlyAnalyze $_class_str`
test -n "$_bug" || exit 4
echo -e "$_bug\n"

$_sendmail $_email "$_pro_name" "$_bug" "author: $_author  comment: $_comment  revision: $_rev"
mysql -uroot -proot -hdb findbugs -e "insert into bugs (project,user,revision,bug,comment,create_time) values ('$_pro_name','$_author','$_rev','${_bug//\'/}','${_comment//\'/}',now())"

echo -e "$_date  author: $_author  revision: $_rev\n"
